/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CryptoIndexRouteImport } from './routes/crypto/index'
import { Route as ApiGoldRouteImport } from './routes/api/gold'
import { Route as ApiFetchCoinsRouteImport } from './routes/api/fetchCoins'
import { Route as ApiHealthMarketDataRouteImport } from './routes/api/health/market-data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoIndexRoute = CryptoIndexRouteImport.update({
  id: '/crypto/',
  path: '/crypto/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoldRoute = ApiGoldRouteImport.update({
  id: '/api/gold',
  path: '/api/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchCoinsRoute = ApiFetchCoinsRouteImport.update({
  id: '/api/fetchCoins',
  path: '/api/fetchCoins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthMarketDataRoute = ApiHealthMarketDataRouteImport.update({
  id: '/api/health/market-data',
  path: '/api/health/market-data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/fetchCoins': typeof ApiFetchCoinsRoute
  '/api/gold': typeof ApiGoldRoute
  '/crypto/': typeof CryptoIndexRoute
  '/api/health/market-data': typeof ApiHealthMarketDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/fetchCoins': typeof ApiFetchCoinsRoute
  '/api/gold': typeof ApiGoldRoute
  '/crypto': typeof CryptoIndexRoute
  '/api/health/market-data': typeof ApiHealthMarketDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/fetchCoins': typeof ApiFetchCoinsRoute
  '/api/gold': typeof ApiGoldRoute
  '/crypto/': typeof CryptoIndexRoute
  '/api/health/market-data': typeof ApiHealthMarketDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/fetchCoins'
    | '/api/gold'
    | '/crypto/'
    | '/api/health/market-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/fetchCoins'
    | '/api/gold'
    | '/crypto'
    | '/api/health/market-data'
  id:
    | '__root__'
    | '/'
    | '/api/fetchCoins'
    | '/api/gold'
    | '/crypto/'
    | '/api/health/market-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFetchCoinsRoute: typeof ApiFetchCoinsRoute
  ApiGoldRoute: typeof ApiGoldRoute
  CryptoIndexRoute: typeof CryptoIndexRoute
  ApiHealthMarketDataRoute: typeof ApiHealthMarketDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/': {
      id: '/crypto/'
      path: '/crypto'
      fullPath: '/crypto/'
      preLoaderRoute: typeof CryptoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gold': {
      id: '/api/gold'
      path: '/api/gold'
      fullPath: '/api/gold'
      preLoaderRoute: typeof ApiGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetchCoins': {
      id: '/api/fetchCoins'
      path: '/api/fetchCoins'
      fullPath: '/api/fetchCoins'
      preLoaderRoute: typeof ApiFetchCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/market-data': {
      id: '/api/health/market-data'
      path: '/api/health/market-data'
      fullPath: '/api/health/market-data'
      preLoaderRoute: typeof ApiHealthMarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFetchCoinsRoute: ApiFetchCoinsRoute,
  ApiGoldRoute: ApiGoldRoute,
  CryptoIndexRoute: CryptoIndexRoute,
  ApiHealthMarketDataRoute: ApiHealthMarketDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
