/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorIndexRouteImport } from './routes/calculator/index'
import { Route as ApiGoldRouteImport } from './routes/api/gold'
import { Route as ApiFetchCoinsRouteImport } from './routes/api/fetchCoins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIndexRoute = CalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoldRoute = ApiGoldRouteImport.update({
  id: '/api/gold',
  path: '/api/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchCoinsRoute = ApiFetchCoinsRouteImport.update({
  id: '/api/fetchCoins',
  path: '/api/fetchCoins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/fetchCoins': typeof ApiFetchCoinsRoute
  '/api/gold': typeof ApiGoldRoute
  '/calculator/': typeof CalculatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/fetchCoins': typeof ApiFetchCoinsRoute
  '/api/gold': typeof ApiGoldRoute
  '/calculator': typeof CalculatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/fetchCoins': typeof ApiFetchCoinsRoute
  '/api/gold': typeof ApiGoldRoute
  '/calculator/': typeof CalculatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/fetchCoins' | '/api/gold' | '/calculator/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/fetchCoins' | '/api/gold' | '/calculator'
  id: '__root__' | '/' | '/api/fetchCoins' | '/api/gold' | '/calculator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFetchCoinsRoute: typeof ApiFetchCoinsRoute
  ApiGoldRoute: typeof ApiGoldRoute
  CalculatorIndexRoute: typeof CalculatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/': {
      id: '/calculator/'
      path: '/calculator'
      fullPath: '/calculator/'
      preLoaderRoute: typeof CalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gold': {
      id: '/api/gold'
      path: '/api/gold'
      fullPath: '/api/gold'
      preLoaderRoute: typeof ApiGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetchCoins': {
      id: '/api/fetchCoins'
      path: '/api/fetchCoins'
      fullPath: '/api/fetchCoins'
      preLoaderRoute: typeof ApiFetchCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFetchCoinsRoute: ApiFetchCoinsRoute,
  ApiGoldRoute: ApiGoldRoute,
  CalculatorIndexRoute: CalculatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
